### ISSUE TITLE
[bug] 高级模式中，当文本中含有「し」、「ち」以及有这两个音的单词时，清理报错，且GUI无法继续正常运行

### ISSUE THREAD

**Issue by Shinkudaisuki** [CjangCjengh/MoeGoe_GUI#1]

**Comment by Shinkudaisuki** [comment]
看了看GUI的源码，并在命令行下运行MoeGoe.exe测试，可能是「し」和「ち」清理后输出的“ʃ”字符导致的问题
![image](https://user-images.githubusercontent.com/111146080/184418953-b7c9ff84-b10e-497a-9a67-864ca53ee8cd.png)

**Comment by CjangCjengh** [comment]
控制面板->时钟和区域->区域->管理->更改系统区域设置->Beta版：使用Unicode UTF-8
